recaptcha {
    // These keys are generated by the ReCaptcha service
    publicKey = "6LeEAgMTAAAAANYBt2DWOLoqWBpQTvpNE82-roQ8"
    privateKey = "6LeEAgMTAAAAADJKBUiJWZvNThYUHpeU4PeP5iWp"

    // Include the noscript tags in the generated captcha
    includeNoScript = true

    // Include the required script tag with the generated captcha
    //includeScript = true

    forceLanguageInURL = false
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
    development {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = true
            // Communicate using HTTPS
            useSecureAPI = true
        }
    }
    production {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = true
            // Communicate using HTTPS
            useSecureAPI = true
        }
    }
}